### ISSUE TITLE
Cannot install umfpack

### ISSUE THREAD

**Issue by DuAlexander** [scikit-umfpack/scikit-umfpack#30] opened 2016-11-03 10:53 UTC
When I use the command: 
`python setup.py install`
I get this error:

> umfpack_info:
  libraries umfpack not found in ['/home/bingxiao/anaconda2/lib']
/home/bingxiao/anaconda2/lib/python2.7/site-packages/numpy/distutils/system_info.py:570: UserWarning: 
    UMFPACK sparse solver (http://www.cise.ufl.edu/research/sparse/umfpack/)
    not found. Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [umfpack]) or by setting
    the UMFPACK environment variable.
  warnings.warn(self.notfounderror.__doc__)
  NOT AVAILABLE

> Traceback (most recent call last):
  File "setup.py", line 186, in <module>
    setup_package()
  File "setup.py", line 183, in setup_package
    setup(**metadata)
  File "/home/bingxiao/anaconda2/lib/python2.7/site-packages/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "setup.py", line 92, in configuration
    config.add_subpackage('scikits.umfpack')
  File "/home/bingxiao/anaconda2/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 1000, in add_subpackage
    caller_level = 2)
  File "/home/bingxiao/anaconda2/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 969, in get_subpackage
    caller_level = caller_level + 1)
  File "/home/bingxiao/anaconda2/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 906, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scikits/umfpack/setup.py", line 19, in configuration
    umf_info['libraries'].insert(0, 'rt')
KeyError: 'libraries'

I am a beginner, can someone help me with this problem?

**Comment by rc** [comment] 2016-11-04 09:51
This package is just a Python wrapper for the UMFPACK sparse solver. To use the wrapper, you need to have UMFPACK installed on your system. For example, on debian-based linux distributions, you would need libsuitesparse-dev, libumfpack5.6.2.

**Comment by DuAlexander** [comment] 2016-11-04 10:21
@rc Thank you! 
My system is Ubuntu, and I have libsuitesparse-dev and libumfpack is version 5.6.1. When I try to update libumfpack use:
`sudo apt-get install --only-upgrade libumfpack`
I get this error:

> Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libumfpack

How should I fix this problem?

**Comment by DuAlexander** [comment] 2016-11-04 10:30
@rc Thank you!
I use ubuntu, and I have  libsuitesparse-dev, and the libumfpack version is 5.7.1.

**Comment by rc** [comment] 2016-11-04 10:37
Those libs you have seem to be OK, you do not need to upgrade (libumfpack5.6.2 is the actual debian package name that I have, not just libumfpack). In that case it seems that numpy distutils cannot find the umfpack libraries. Try locating ``numpy/distutils/site.cfg`` in your anaconda and adding the paths there. I do not really know what the problem is, as I use the standard ubuntu Python and packages, not anaconda's.

BTW. https://github.com/conda-forge/scikit-umfpack-feedstock does not work for you?

**Comment by DuAlexander** [comment] 2016-11-04 14:58
@rc I tried the link of conda-forge you gave, but there was some compatibility problem:
![image](https://cloud.githubusercontent.com/assets/18528263/20006921/d04db56a-a291-11e6-8fd0-9898ce8676fc.png)

So I try to add path.  When I locate the `numpy/distutils/site.cfg`, it shows:
![image](https://cloud.githubusercontent.com/assets/18528263/20006995/2da5a844-a292-11e6-97a7-00b342d44ee8.png)

I open one of them:
![image](https://cloud.githubusercontent.com/assets/18528263/20010200/21b499ac-a29f-11e6-8b6a-cfb40146b791.png)

Now how should I add the parth?

**Comment by grlee77** [comment] 2016-11-04 15:37
In the conda recipe, we do not modify site.cfg, but instead set a "UMFPACK" environment variable.  Below is what is in the (bash shell) build script for OS X and linux:

```
export UMFPACK="${PREFIX}/lib"

$PYTHON setup.py install --single-version-externally-managed --record record.txt
```

If you go the site.cfg route, if I recall correctly you can place a site.cfg within the folder that you are running setup.py from instead of modifying the numpy one.  You would add a [umfpack] section following the [mkl] example in your post above with the appropriate include/lib paths for your system.

**Comment by grlee77** [comment] 2016-11-04 15:38
Forgot to mention in the example bash script above, you would need to change `${PREFIX}\lib` to the appropriate folder containing the umfpack library on your system.

**Comment by rc** [comment] 2016-11-09 09:22
@grlee77 thanks for the advice, I forgot about the local site.cfg possibility. @DuAlexander any updates?

**Comment by DuAlexander** [comment] 2016-11-09 10:35
@grlee77  @rc thank you! I changed the site.cfg, and scikit-umfpack seems to be installed successfully. Whether this approach will cause some problem?  Or is the set environment approach a better way to fix this problem?  

As I installed this package as dependency for another package called `sfepy`,  but I haven't successfully intalled `sfepy.`

**Comment by rc** [comment] 2016-11-09 10:49
@DuAlexander IMHO those approaches are both OK and should not cause problems with other packages. FYI: https://github.com/conda-forge/staged-recipes/pull/1835.

**Comment by DuAlexander** [comment] 2016-11-09 11:04
@rc thanks so much for the recipes!

**Comment by rc** [comment] 2016-11-09 11:25
@DuAlexander the recipe is not merged yet, but we hope to have everything fixed soon. As for this issue, let us close it.

**Closed by rc** 2016-11-09 11:25 UTC
