### ISSUE TITLE
Does not build with Clang on macOS

### ISSUE THREAD

**Issue by szhorvat** [scikit-umfpack/scikit-umfpack#94] opened 2023-11-20 16:18 UTC
This package does not seem to build with Clang, which is the system compiler on macOS. The build system tries to invoke `cc -print-sysroot`, but this option is specific to GCC and not available with Clang.

Do you have any advice on how to work around this?

Please see here for the PR trying to update this package in MacPorts:

https://github.com/macports/macports-ports/pull/21493

**Comment by rc** [comment] 2023-11-20 17:18
I will then make a quick 0.4.1 release...

**Comment by szhorvat** [comment] 2023-11-20 17:40
Thanks for the super quick response!

The update in MacPorts is being done in the context of updating SuiteSparse from 5.x to 7.3.1. As I understand, UMFPACK is (mostly?) source-compatible between these two releases, but the build system was changed to CMake. Just to know what to anticipate in MacPorts, have you tested `scikit-umfpack` with a recent SuiteSparse? I see that the CI here uses SuiteSparse 5.10.

**Comment by rgommers** [comment] 2023-11-20 20:07
Ah indeed, it's kinda curious that both Ubuntu and Conda-forge have SuiteSparse 5.10.1. I had expected Conda-forge to be more up-to-date, but it looks like no one put in the effort yet to work through the changes in 6.0

**Comment by rgommers** [comment] 2023-11-20 20:11
So to answer the question - I did not build a more recent SuiteSparse from source. It looks like @rc has, but the result hasn't landed yet: gh-80

**Comment by szhorvat** [comment] 2023-11-20 20:43
SuiteSparse has lots of sub-packages, and they may have changed in different ways. But so far, no package in MacPorts was broken by the SuiteSparse update. If there are any issues at all, I'd expect them to relate to the build system (finding headers and libraries), not the compilation or functionality.

**Comment by rgommers** [comment] 2023-11-21 12:28
This should be fixed by gh-95. For macOS it adds an x86-64 CI job, and I've tested on arm64 as well.

**Closed** 2023-11-21 15:30 UTC

**Comment by rc** [comment] 2023-11-21 15:34
Let us know, please, if the problem is fixed for you. I will then make 0.4.1.

**Comment by jjstickel** [comment] 2023-11-21 15:42
Yes, it builds now on Mac with the Mac-specific patch applied. You don't need to make the release right away for Macports use (we can apply the patch as part of our install process).

**Comment by rc** [comment] 2023-11-21 15:45
OK, thanks for the confirmation.

**Comment by szhorvat** [comment] 2023-11-21 16:34
I was looking if I could build this package with SuiteSparse 7.x, and it seems it's looking for a bunch of headers that are no longer available:

https://github.com/scikit-umfpack/scikit-umfpack/blob/a9c58b8a00197f9c88d9482f9d78c076c37b1700/scikits/umfpack/umfpack.i#L218-L229

These headers are present in SuiteSparse 5.x:

https://github.com/DrTimothyAldenDavis/SuiteSparse/tree/v5.13.0/UMFPACK/Include

But not in SuiteSparse 7.x:

https://github.com/DrTimothyAldenDavis/SuiteSparse/tree/v7.3.1/UMFPACK/Include

Are you sure that directly accessing these headers (instead of simply including `umfpack.h`) was ever part of the public UMFPACK API?

**Comment by rgommers** [comment] 2023-11-21 16:55
@rc is working on a fix for that right now I see: gh-80.

> Are you sure that directly accessing these headers (instead of simply including `umfpack.h`) was ever part of the public UMFPACK API?

Personally I have no idea, but I'd say that if they weren't public, they shouldn't have been installed right next to the public one without as much as an underscore.

**Comment by szhorvat** [comment] 2023-11-21 17:08
I managed to build it after commenting out all `%include`s except for `umfpack.h`. But I am not familiar with SWIG and I don't know if this would break it for earlier SuiteSparse. The change is mentioned here: https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v6.0.0

**Comment by rc** [comment] 2023-11-21 17:59
The single header file is "new" from the version 6, which is not yet supported. But see #80 - can you try that version?

**Comment by szhorvat** [comment] 2023-11-21 20:36
> But see #80 - can you try that version?

I get this error:

```
  [1/3] Generating scikits/umfpack/_umfpack_swig with a custom command
  FAILED: scikits/umfpack/_umfpack_wrap.c scikits/umfpack/_umfpack.py
  /opt/local/bin/swig -python -I/opt/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include -o scikits/umfpack/_umfpack_wrap.c -outdir scikits/umfpack ../scikits/umfpack/umfpack.i
  :3: Error: Unable to find 'python.swg'
  ../scikits/umfpack/umfpack.i:263: Error: Unable to find 'typemaps.i'
  ninja: build stopped: subcommand failed.
  error: subprocess-exited-with-error
```

**Comment by rc** [comment] 2023-11-21 20:47
Strange - it should not differ from what you did (if `UMFPACK_MAIN_VERSION` is not lower than 6, and that constant is defined in `umfpack.h`).

**Comment by szhorvat** [comment] 2023-12-22 13:19
`scikit-umfpack` is last blocker for [updating SuiteSparse in MacPorts](https://github.com/macports/macports-ports/pull/21451). Did you manage to get it working with post-5.x SuiteSparse versions, and are there plans for an imminent release?

You asked me to help with testing, which is entirely fair, since I brought up this issue. But I need to be realistic about how much I can commit. Given my inexperience with meson, SWIG and Python packages in general, and my current workload, I won't be able to do much. It's better if I'm upfront about this.

I'm just looking for some input about what to expect regarding SuiteSparse 7.0 compatibility in the near future :-)

**Comment by DrTimothyAldenDavis** [comment] 2023-12-22 14:32
Checkout SuiteSparse 7.4.0.beta8.  The build system is much improved and it should work for clang.

**Comment by szhorvat** [comment] 2023-12-22 14:39
There's still the issue with supporting both multi-header and single-header UMFPACK. As I understand this is up to scikit-umfpack and won't be affected by SuiteSparse's build system.

**Comment by szhorvat** [comment] 2023-12-26 15:26
I'm sorry, I did not realize that you already released the fix. I confirm that it works fine in MacPorts.

**Comment by DrTimothyAldenDavis** [comment] 2023-12-26 15:30
Thanks for the update.  Is there anything else in SuiteSparse itself that needs to be fixed for MacPorts or scikit?  I'd like to post a stable SuiteSparse 7.4.0 soon, but I'd also like to make sure it works for you first.

**Comment by szhorvat** [comment] 2023-12-26 15:45
@DrTimothyAldenDavis No, everything looks good. There's the ParU issue that I told you about, but for now I will just skip including ParU. I will finalize the PR to MacPorts after you issue the final 7.4.0 release.

**Comment by DrTimothyAldenDavis** [comment] 2023-12-26 15:50
That sounds like a good plan. 

My goal is to post a stable SuiteSparse 7.4.0 on Dec 30.
